name: ci-cd-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: simple_bank
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

    - name: Set up Go 
      uses: actions/setup-go@v4
      with:
        go-version: '^1.23'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Install go-migrate
      run: |
        curl -L https://packagecloud.io/golang-migrate/migrate/gpgkey | apt-key add -
        sudo echo "deb https://packagecloud.io/golang-migrate/migrate/ubuntu/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/migrate.list
        sudo apt-get update
        sudo apt-get install -y migrate
        which migrate

    - name: Run migration
      run: make migrateup

    - name: Test
      run: make test
